apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: go-web-service-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/JamesTiberiusKirk/form3homework
  ref:
    branch: main
