apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-web-service
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/go-web-service
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: go-web-service-repo
        namespace: flux-system
  values:
    image:
      repository: localhost:5000/go-web-service
      tag: latest
